name: Python environment
on: [push, pull_request]

jobs:
  install-python:
    runs-on: windows-latest
    
    steps:
     - uses: actions/checkout@v2
     - name: Install python
    
       uses: gabrielfalcao/pyenv-action@v7
       with:
          default: 3.9.6 # pick version 3.8.6
          command: pip install -U pip
        
     - name: create environment
       run: pyenv local 3.8.6 && python -mvenv .venv386
       
     - name: Install dependencies
       run: pip install -r requirements.txt --upgrade pip
       
       
     - name: setup pyenv
       id: pyenv_installation
       uses: "gabrielfalcao/pyenv-actionv@7"
       
     - name: debug pyenv
       env: 
        GOOGLE_CLOUD_SPEECH_CREDENTIALS: ${{ secrets.GOOGLE_CLOUD_SPEECH_CREDENTIALS }} 
       run: echo ${{ steps.pyenv_installation.outputs.pyenv_root }}
